### ISSUE TITLE
Support passing reactions through the bridge

### ISSUE THREAD

**Issue by pravi** [maranda/matrix-bifrost#9]
Some xmpp clients have started implementing reactions (dino, movim for example) and it'd be good to pass reactions through the bridge both ways.

**Comment by pravi** [comment]
this is https://xmpp.org/extensions/xep-0444.html

**Comment by bleonard252** [comment]
I tried implementing this and found out it's not possible. Since XEP-0444 uses a refreshing list of reactions per user, and Matrix uses a deletable one message per reaction approach, the two aren't compatible, and porting can't be done without being able to read other messages, which isn't available for Bifröst to do on either end.
